import { IWeatherState, IForecast } from "../IWeatherWebPartProps";

export const mockWeatherState: IWeatherState = {
  IsDayTime: true,
  city: "Perm",
  country: "Russia",
  key: "294922",
  pressure: "1016 mb",
  realFeelTemperature: "-25° C",
  temp: "-18°  C",
  time: "January 22, 2021",
  visibility: "8 km",
  weatherIcon: 20,
  weatherText: "Light snow",
  windDirect: "ENE",
  windSpeed: "8.1  mi/h",
};

export const mockForecast: IForecast[] = [
  {
    key: "294922",
    date: "2 февраля",
    dayIcon: 20,
    dayIconText: "Mostly cloudy w/ flurries",
    nightIcon: 8,
    tempDay: "-5 ° C",
    tempNight: "-12 ° C",
    weekday: "вторник",
  },
  {
    date: "3 февраля",
    dayIcon: 8,
    dayIconText: "Dreary",
    key: "294922",
    nightIcon: 7,
    tempDay: "-8 ° C",
    tempNight: "-15 ° C",
    weekday: "среда",
  },
  {
    date: "4 февраля",
    dayIcon: 19,
    dayIconText: "Flurries",
    key: "294922",
    nightIcon: 22,
    tempDay: "-6 ° C",
    tempNight: "-6 ° C",
    weekday: "четверг",
  },
  {
    date: "5 февраля",
    dayIcon: 22,
    dayIconText: "Snow",
    key: "294922",
    nightIcon: 8,
    tempDay: "-1 ° C",
    tempNight: "-5 ° C",
    weekday: "пятница",
  },
  {
    date: "6 февраля",
    dayIcon: 7,
    dayIconText: "Cloudy",
    key: "294922",
    nightIcon: 22,
    tempDay: "-5 ° C",
    tempNight: "-17 ° C",
    weekday: "суббота",
  },
];
